### ISSUE TITLE
last_name required when registering using REST

### ISSUE THREAD

**Issue by aman-gautam** [dreamfactorysoftware/dsp-core#104]
DSP version: 2.0

1. Enable open registration in User service
2. Send a request to /rest/user/register with data {"email": "user@example.com"} and appropriate headers

Response:

    {
        "error": {
            "context": {
                "last_name": [
                    "The last name field is required."
                ]
            },
            "message": "Validation failed",
            "code": 400,
            "trace": []
        }
    }

Is it a normal behavior to have last_name as a required field?

**Comment by jstablesdf** [comment]
This is a 2.0 issue. Should be posted in the [dreamfactory](https://github.com/dreamfactorysoftware/dreamfactory) repository. [dsp-core](https://github.com/dreamfactorysoftware/dsp-core/) is 1.x only.
