### ISSUE TITLE
Product Support dialog doesn't allow no

### ISSUE THREAD

**Issue by jonmountjoy** [dreamfactorysoftware/dsp-core#36]
Just deployed via the Heroku Button.

I get to this point:

![dreamfactory services platform](https://cloud.githubusercontent.com/assets/545244/4286348/9fa3009c-3d93-11e4-82eb-74c7c62d02e3.png)

Clicking No just returns me to the same page.

**Comment by jstablesdf** [comment]
This should no longer apply to the new Admin Console UI. Please document and reopen if encountered again. https://github.com/dreamfactorysoftware/dsp-core/commit/9d53a264ec2b98ec1f0f516648ac917877cf5b89
