### ISSUE TITLE
date fields in Data Manager are not shown

### ISSUE THREAD

**Issue by spackmat** [dreamfactorysoftware/dsp-core#52]
Hi,

maybe I am missing something, but the Data Manager does not show any inputs for fields of the type *date*. There is just a label on the edit vies. The list view shows the values correctly, despite the fact that I cannot show or hide the *date* fields, they are just all visible.

Greets,
spackmat

**Comment by jstablesdf** [comment]
To resolve, date fields have been changed to text fields instead of date pickers. This is not an ideal solution but does allow editing for now. This fix is included in 1.9.0.
