### ISSUE TITLE
Feature request: confirmation dialog on script deletion

### ISSUE THREAD

**Issue by antonyjsmith** [dreamfactorysoftware/dsp-core#53]
I'd like to suggest adding an 'are you sure' pop up [or similar] to the delete button in server side scripting.

It's right next to the save button and one errant touch with a trackpad that has tap to click enabled and boom...... your script has gone...... before any one asks, yes I did.......

**Comment by jstablesdf** [comment]
This was added in December and included in the 1.9.0 release https://github.com/dreamfactorysoftware/dsp-core/commit/9d53a264ec2b98ec1f0f516648ac917877cf5b89
