### ISSUE TITLE
Calling custom script from API Docs causes 403 error

### ISSUE THREAD

**Issue by jstablesdf** [dreamfactorysoftware/dsp-core#55]
There is a problem calling custom scripts from the API docs in the WAMP install package. After calling a script via the API Docs, the scripting engine becomes unavailable and throws 403 errors, until a restart of Apache. Scripting will work from test_rest.html until it is called again from the API Docs, at which point it resumes failing.

**Comment by ibnIrshad** [comment]
Just adding that I have this problem on Ubuntu Linux, not WAMP, in DSP version 1.8.0, and I'm getting a 404, not a 403. After creating a custom script called "test" (without the quotes), trying to access it with the REST API or API Docs gives me this 404 error: &quot;test&quot; was not found. However the script is visible at /rest/system/script

The DSP core seems to be wrapping the script name with  &quot; unnecessarily.

**Comment by isaacplmann** [comment]
This doesn't only happen when calling via the API docs.

When I call a script through the normal process, about half the time I get a 500 error.

The error is this:
        <h3>Error Details</h3>

        <div class="inset">
            <p>V8Js::__construct(): Failed to create V8 context. Check that registered extensions do not have errors.</p>
        </div>

**Comment by jstablesdf** [comment]
This is a known issue with V8js on Windows. I don't believe a resolution will be back-applied to the 1.x product.
