### ISSUE TITLE
Schema Manager column action buttons don't line up with column

### ISSUE THREAD

**Issue by delebash** [dreamfactorysoftware/dsp-core#57]
The delete (trash can icons) don't line up with their perspective columns.  You can see in the attached pic that the id columns trash can is in the name column's box and the name columns trash can is outside below the name column border box.

![screenshot 5](https://cloud.githubusercontent.com/assets/2220160/5292780/d13c134e-7b34-11e4-9001-9a4fd63e08f6.jpg)

**Comment by jstablesdf** [comment]
This problem no longer applies in the new Admin Console UI.
