### ISSUE TITLE
Cannot refer to User table as foreign key

### ISSUE THREAD

**Issue by jstablesdf** [dreamfactorysoftware/dsp-core#64]
Cannot access the system User table when using "related" URI parameter to retrieve related data.

**Comment by jstablesdf** [comment]
This is JIRA DF-78

**Comment by aman-gautam** [comment]
Any update on this issue? Is it there in 2.0?

**Comment by jstablesdf** [comment]
This is not permitted and was not a bug. For security reasons, you are not permitted to fetch the user as a related record. `related=*` includes the user table, which is not accessible by the service making the request.

However it is in the development backlog to determine a way around this, allowing fetching user data as related data without posing a security risk. It will not be added to 1.x, and is not currently implemented in 2.0.
