### ISSUE TITLE
No mentions of PHP 5.4 requirement

### ISSUE THREAD

**Issue by Glitchbone** [dreamfactorysoftware/dsp-core#67]
Please add to the documentation that Dreamfactory requies PHP 5.4 or higher due to the usage of the JSON_UNESCAPED_SLASHES constant

**Comment by jstablesdf** [comment]
I'm not sure this is a bug in the code of dsp-core. I will review with the engineers.

**Comment by jstablesdf** [comment]
@Glitchbone You are correct that `JSON_UNESCAPED_SLASHES` was not introduced until PHP 5.4.0 and that we use it. I do not believe this is a bug.

http://php.net/manual/en/json.constants.php

**Comment by Glitchbone** [comment]
Thanks for your reply. I didn't say it was a bug but I think the minimum requirement of PHP 5.4 must appear somewhere in the wiki

**Comment by jstablesdf** [comment]
The wiki also says the current version is 1.8. :) I agree we need to make some updates.

**Comment by jstablesdf** [comment]
I have added this requirement to the Add-ons and Drivers page under "Non-Bitnami Installs" since Bitnami ships DSP with PHP 5.4 at this time and soon with 5.5.

https://github.com/dreamfactorysoftware/dsp-core/wiki/Additional-Drivers
