### ISSUE TITLE
Change or Add field for user

### ISSUE THREAD

**Issue by MrSaman** [dreamfactorysoftware/dsp-core#68]
Hello
for a improvmemt i suggest you add this feature to dsp.

It is best feature for android device to manage user registration field...

Thank a lot...

**Comment by jstablesdf** [comment]
I'm sorry, I am having difficulty understanding this request. Could you outline what present functionality you'd like to improve and how, or how this new feature would function?

**Comment by mrsaman** [comment]
For example i would like to add PhoneNumber to user table.
also make Setter & Getter in android library and register user with this feature....

Sorry for my bad english

**Comment by jstablesdf** [comment]
I'm sorry, but I still don't know what you need. The user table already stores a phone number. This value is POSTable and GETable via `/rest/user/profile` as well as the Admin Console UI. E.g.,

    POST http://localhost/rest/user/profile

    {
      "email": "user@domain.com",
      "first_name": "User",
      "last_name": "Name",
      "display_name": "User Name",
      "phone": "404-555-5555"
    }

Fields other than those already included may be created manually in the DSP's local database, or added as JSON content via the `/user/custom` settings made available though the API.

**Comment by ibnIrshad** [comment]
Yep I think OP was not aware of `/user/custom`, which is what he is looking for. I would close this issue.

**Comment by jstablesdf** [comment]
Agreed.
