### ISSUE TITLE
How to call remote db ?

### ISSUE THREAD

**Issue by glemiere** [dreamfactorysoftware/dsp-core#79]
Hi !
I created a service names "sql". My problem is that I don't understand two things.
First : How to connect my new API ?
```javascript
    var dsp_url = "http://localhost/rest/sql";
    var app_name = "api";
```

When I'm trying to loggin, my console tell me : <code>Uncaught TypeError: window.app.login is not a function</code>. I can only loggin with : 
```javascript
    var dsp_url = "http://localhost/rest/api_docs";
```

The second thing is easier : have you got an example of ajax call using jquery to use this API ?

**Comment by jstablesdf** [comment]
Hi, these are good questions, but I think they're more documentation and education than issues with the software. I am going to close this GitHub issue, but please send me an email at dspsupport@dreamfactory.com and I'll get you all the resources and instruction that you need. In the future, we have a public forum at [community.dreamfactory.com](http://community.dreamfactory.com/) that's a great place to ask questions and get examples.
