### ISSUE TITLE
Invalid user name and password combination

### ISSUE THREAD

**Issue by RichardPh** [dreamfactorysoftware/dsp-core#81]
deploy on ubuntu. After I complete the initialized, then log out. When I input the URL in the location, press enter, it turned blank. I cant not image what happened. The develop tool told me It can not find the `config` and return the message
`code: 400
context: null
message: "Invalid user name and password combination."`

**Comment by jstablesdf** [comment]
I'm not certain this is a bug in the code. Please contact us at dspsupport@dreamfactory.com so that we can help you.
