### ISSUE TITLE
Create User with Suspended State and Activate them with custom URL

### ISSUE THREAD

**Issue by Rajavasanthan** [dreamfactorysoftware/dsp-core#89]
Hello,
First i will explain what i need in DSP. After that i will explain the problem which i am facing.

I want to create a user registration form my back end is DSP and front end is Angular,

My open Registration options is enabled in DSP, Initially when registering a user with the URL "https://<APP-NAME>.cloud.dreamfactory.com:443/rest/user/register" The user's Conformation column and Active Column should be set to FALSE. After the Success Registration i need to send a E-Mail with my custom URL to the mail ID (NOTE :  i like to have the activation code in URL itself ). 

The user should redirect to my website after clicking the URL in mail  (NOT TO DREAM FACTORY WEBSITE). from there i should retrieve the activation code from the URL and generate a POST request from angular to make the Active Column and Conformation column to SET TRUE.

Now i will explain the problem i am facing.

I created the POST request to register user with URL 
"https://APP-NAME.cloud.dreamfactory.com:443/rest/user/register" 

{
                    'display_name' : NAME,
                    'email' : EMAIL,
                    'first_name' : FIRST NAME,
                    'last_name' : LAST NAME,
                    'new_password' : PASSWORD,
                    'is_active' : false,
                    'confirmed' : false 
}

but "is_active" and "confirmed" column is not setting to false. its still TRUE in DSP admin panel. I don't know why.

After this 

It will be helpful for me if anyone explain how to generate a activation code and pass it through URL and receive in Angular.. After that How to post request to DSP and make that particular user Active and Confirmed.

Thanks in Advance.

**Comment by drewpearce** [comment]
Not an issue for development. This is a support request.
