### ISSUE TITLE
Error 500 when create DSP program.

### ISSUE THREAD

**Issue by lgeeking** [dreamfactorysoftware/dsp-core#94]
I gona to create DSP self-installed ,and I got this error when first login:

Error 500

Internal Server Error
Error Details

System data creation failure (df_sys_service): CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dreamfactory`.`df_sys_service`, CONSTRAINT `fk_df_sys_service_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `df_sys_user` (`id`))

Array
(
    [_viewFile_] => /opt/dreamfactory/platform/app/views/web/error.php
    [_data_] => Array
        (
            [current_user] => CWebUser Object
                (
                    [allowAutoLogin] => 1
                    [guestName] => Guest
                    [loginUrl] => Array
                        (
                            [0] => web/login
                        )

                    [identityCookie] => 
                    [authTimeout] => 
                    [autoRenewCookie] => 
                    [autoUpdateFlash] => 1
                    [loginRequiredAjaxResponse] => 
                    [_keyPrefix:CWebUser:private] => 2834b10ce4cbd5133226f4bbb6cb3fef
                    [_access:CWebUser:private] => Array
                        (
                        )

                    [behaviors] => Array
                        (
                        )

                    [_initialized:CApplicationComponent:private] => 1
                    [_e:CComponent:private] => 
                    [_m:CComponent:private] => 
                )

            [code] => 500
            [type] => DreamFactory\Platform\Exceptions\InternalServerErrorException
            [errorCode] => 500
            [message] => System data creation failure (df_sys_service): CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dreamfactory`.`df_sys_service`, CONSTRAINT `fk_df_sys_service_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `df_sys_user` (`id`))
            [file] => /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-platform/src/Services/SystemManager.php
            [line] => 1214
            [trace] => #0 /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-platform/src/Services/SystemManager.php(542): DreamFactory\Platform\Services\SystemManager::_createSystemData('service', Array, 'DreamFactory\Pl...', 'api_name')
#1 /opt/dreamfactory/platform/app/controllers/WebController.php(369): DreamFactory\Platform\Services\SystemManager::initData()
#2 /opt/dreamfactory/platform/app/controllers/WebController.php(1250): WebController->actionInitData()
#3 /opt/dreamfactory/platform/app/controllers/WebController.php(1207): WebController->_handleAction(1)
#4 /opt/dreamfactory/platform/app/controllers/WebController.php(185): WebController->_checkSystemState()
#5 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3911): WebController->actionIndex()
#6 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3423): CInlineAction->runWithParams(Array)
#7 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6425): CController->runAction(Object(CInlineAction))
#8 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6434): CFilterChain->run()
#9 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3801): CFilter->filter(Object(CFilterChain))
#10 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6467): CController->filterAccessControl(Object(CFilterChain))
#11 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(6422): CInlineFilter->filter(Object(CFilterChain))
#12 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3413): CFilterChain->run()
#13 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(3398): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1745): CController->run('')
#15 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1665): CWebApplication->runController('')
#16 /opt/dreamfactory/platform/vendor/dreamfactory/yii/framework/yiilite.php(1190): CWebApplication->processRequest()
#17 /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-yii/src/Utility/Pii.php(219): CApplication->run()
#18 /opt/dreamfactory/platform/web/index.php(69): DreamFactory\Yii\Utility\Pii::run('/opt/dreamfacto...', Object(Composer\Autoload\ClassLoader), 'DreamFactory\Pl...')
#19 {main}
            [traces] => Array
                (
                    [0] => Array
                        (
                            [file] => /opt/dreamfactory/platform/vendor/dreamfactory/lib-php-common-platform/src/Services/SystemManager.php
                            [line] => 542
                            [function] => _createSystemData
                            [class] => DreamFactory\Platform\Services\SystemManager
                            [type] => ::
                            [args] => Array
                                (
                                    [0] => service
                                    [1] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [api_name] => db
                                                    [name] => Database
                                                    [is_active] => 1
                                                    [type] => Local SQL DB
                                                    [type_id] => 4
                                                    [description] => Local database access
                                                )

                                         ................
....................................
......................

    [_niceCode] => Internal Server Error
)

**Comment by drewpearce** [comment]
This is not a bug/issue. It is a support request. Please contact dreamfactory support ( http://www.dreamfactory.com/developers/support ) or visit the community for help with your installation ( http://community.dreamfactory.com/ )
