### ISSUE TITLE
Renaming dreamfactory (application name) on openshift

### ISSUE THREAD

**Issue by m-menon** [dreamfactorysoftware/dsp-core#98]
Just curious - if i rename the application name when deploying the below cartridge to openshift, would it cause any problems? I mean has anyone encountered such a thing?

rhc app create dreamfactory php-5.4 mysql-5.5 --from-code https://github.com/dreamfactorysoftware/dsp-core.git

I am totally new to openshift and dreamfactory and didn't want to take a chance. I hope that doesn't sound stupid but I didn't want to learn it the wrong way :)

**Comment by jstablesdf** [comment]
You should be able to deploy on OpenShift with any cartridge name you wish. Let us know if you encounter an issue!

**Comment by m-menon** [comment]
Thanks a lot. I was able to deploy the cartridge with a different name.
